[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "true"
  # Use the Neon PostgreSQL database in Netlify
  DATABASE_URL = "postgresql://neondb_owner:npg_ToXGaN5W0wvE@ep-jolly-rice-a5lawqbw-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["@prisma/client", "bcrypt"]
  node_bundler = "esbuild"

# No direct redirects needed - Next.js plugin handles this 