[build]
  command = "prisma generate && npm run build"
  publish = ".next"

[build.environment]
  # Do not skip the Next.js plugin - we want to use it
  # NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Uncomment and set these values in Netlify dashboard environment variables instead
  # DATABASE_URL = ""
  # NEXTAUTH_URL = ""
  # NEXTAUTH_SECRET = ""

[[plugins]]
  package = "@netlify/plugin-nextjs" 