[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "true"
  # Note: DATABASE_URL should be set in Netlify UI environment variables
  # with a PostgreSQL connection string

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["@prisma/client", "bcrypt"]
  node_bundler = "esbuild"

# No direct redirects needed - Next.js plugin handles this 